//@hostname = 192.168.20.1
//@hostname = 192.168.1.22
//@hostname = 10.0.0.15
@hostname = 127.0.0.1
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json

### get device infos
http://{{host}}/info


### get device infos
http://{{host}}/info?space

### get file
@id = 8064b86a-c22a-11eb-a21f-08d23e367d1f
http://{{host}}/files/{{id}}/analysis_results.json


### measure
POST http://{{host}}/sequence

{
    "sequence_interval" : 1,
    "sequence_count" : 50,
    "color_depth": "8bits",
    "awb": "off",
    "exposure": 60,
    "gain_master": 50,
    "gain_red": 50,
    "gain_green": 0,
    "gain_blue": 10,
    "LEDs_params": {
        "uv": {
            "intensity": 255,
            "status": "enabled"
        },
        "visible": {
            "intensity": 0,
            "status": "disabled"
        }
    }
}

### simulation
http://{{host}}/simulation?step=Algo5&repeat=15

### set leds intensity
POST http://{{host}}/leds/visible

{
    "status" : "enfable",
    "intensity" : 40
}

### set leds intensity
POST http://{{host}}/leds/uv

{
    "status" : "enable",
    "intensity" : 129
}

### set leds intensity
POST http://{{host}}/leds/uv

{
    "status" : "disable"
}

### snapshot
POST http://{{host}}/snapshot

{
    "color_depth": "8bits",
    "awb": "off",
    "exposure": 30,
    "gain_master": 30,
    "gain_red": 40,
    "gain_green": 0,
    "gain_blue": 10,
    "color_channel": "red",
    "roi_x": 800,
    "roi_y": 140,
    "roi_width": 240,
    "roi_height": 240
}

### snapshot
POST http://{{host}}/snapshot

{
    "exposure": 50,
    "roi_size": "full"
}

### measure
POST http://{{host}}/measure

{
    "patient_id" : "aze",
    "strip_type" : "ch12"
}

### measure
POST http://{{host}}/calibration-measure

{
}


### measure
POST http://{{host}}/calibration-measure

{
    "croppingPnbvaram": {
        "LEDs_params": {
            "uv": {
                "intensity": 40,
                "status": "enabled"
            },
            "visible": {
                "intensity": 0,
                "status": "disabled"
            }
        },
        "exposure": 30,
        "led_delay": 1350,
        "led_duration": 200,
        "brightness": 9,
        "contrast": 8,
        "saturation": 7,
        "hue": 2
    },
    "acquisitionParam": {
        "exposure": 60,
        "saturation": 7,
        "brightness": 7,
        "contrast": 8,
        "hue": 0,
        "LEDs_params": {
            "uv": {
                "intensity": 150,
                "status": "enabled"
            },
            "visible": {
                "intensity": 0,
                "status": "disabled"
            }
        },
        "isValid": true,
        "strip_packaging": "cassette"
    }
}


### measure
POST http://{{host}}/calibration-measure

{"croppingParam":
{"cropping_param":true,
"LEDs_params":
{"uv":{"intensity":0,"status":"disabled"},"visible":{"intensity":1,"status":"enabled"}},
"exposure":30,"brightness":8,"contrast":8,"saturation":7,"hue":0,"snapshot_delay":200},
"acquisitionParam":
{"LEDs_params":{"uv":{"status":"enabled","intensity":129},"visible":{"status":"disabled","intensity":0}},
"isValid":true,"brightness":4,"contrast":8,"exposure":10,"hue":0,"saturation":7,"strip_packaging":"strip"},
"cassetteName":"K701BT_BL"}

//{"croppingParam__":{"cropping_param":true,"LEDs_params":{"uv":{"intensity":50,"status":"enabled"},"visible":{"intensity":0,"status":"disabled"}},"exposure":60},"acquisitionParam":{"LEDs_params":{"uv":{"status":"enabled","intensity":76},"visible":{"status":"disabled","intensity":0}},"isValid":true,"color_depth":"8bits","awb":"off","exposure":60,"gain_master":50,"gain_red":50,"gain_green":0,"gain_blue":10,"strip_packaging":"cassette"}}


### get file
GET http://{{host}}/files/calibration/raw_picture.png


# {
#     "strip_type": "calibration",
#   "awb": "off",
#   "exposure": "60",
#   "gain_master": "20",
#   "gain_red": "90",
#   "gain_green": "20",
#   "gain_blue": "20",
#   "LEDs_params": {
#     "visible": {
#       "status": "disabled",
#       "intensity": 25
#     },
#     "uv": {
#       "status": "enabled",
#       "intensity": 243
#     }
#   }
# }

### measure
http://{{host}}/calibration-measure



### measure
POST http://{{host}}/diagnostics

{
    "type" : "light_sensors",
    "led_intensity" : 220,
    "duration" : 60
}

### Browse Patients
http://{{host}}/browse?



### study
POST http://{{host}}/studies

{
  "study": "study1",
  "snapshot": "study1_0pgml_N01",
  "date" : "20210715",
  "cassette_name" : "K701WT_SE",
  "compute_concentration" : false,
  "params" : [{
    "awb": "off",
    "exposure": "60",
    "gain_master": "20",
    "gain_red": "90",
    "gain_green": "20",
    "gain_blue": "20",
    "LEDs_params": {
      "visible": {
        "status": "disabled",
        "intensity": 25
      },
      "uv": {
        "status": "enabled",
        "intensity": 243
      }
    }
  },{
    "awb": "off",
    "exposure": "50",
    "gain_master": "30",
    "gain_red": "90",
    "gain_green": "20",
    "gain_blue": "20",
    "LEDs_params": {
      "visible": {
        "status": "disabled",
        "intensity": 25
      },
      "uv": {
        "status": "enabled",
        "intensity": 255
      }
    }
  }]
}



### study lmx3
POST http://{{host}}/studies

{
  "study": "study1",
  "snapshot": "study1_0pgml_N01",
  "date" : "20210715",
  "cassette_name" : "K701WT_SE",
  "compute_concentration" : false,
  "params" : [{
    "exposure" : 60,
    "brightness": "8",
    "contrast": "10",
    "saturation": "10",
    "hue": "-2",
    "LEDs_params": {
      "visible": {
        "status": "disabled",
        "intensity": 25
      },
      "uv": {
        "status": "enabled",
        "intensity": 243
      }
    }
  },{
    "exposure" : 150,
    "brightness": "4",
    "contrast": "12",
    "saturation": "12",
    "hue": "2",
    "LEDs_params": {
      "visible": {
        "status": "disabled",
        "intensity": 25
      },
      "uv": {
        "status": "enabled",
        "intensity": 255
      }
    }
  },{
    "brightness": "6",
    "contrast": "12",
    "saturation": "12",
    "hue": "0",
    "LEDs_params": {
      "visible": {
        "status": "disabled",
        "intensity": 25
      },
      "uv": {
        "status": "enabled",
        "intensity": 255
      }
    }
  },{
    "brightness": "4",
    "contrast": "12",
    "saturation": "14",
    "hue": "10",
    "LEDs_params": {
      "visible": {
        "status": "disabled",
        "intensity": 25
      },
      "uv": {
        "status": "enabled",
        "intensity": 255
      }
    }
  }]
}

### study
DELETE http://{{host}}/studies?study=azeaze&snapshot=azeaze_2pgml_N01


###
delete http://192.168.0.34:8080/studies?study=azeaze&snapshot=azeaze_2pgml_N02

###
options http://192.168.0.34:8080/studies?study=azeaze&snapshot=azeaze_2pgml_N02
Access-Control-Request-Method: DELETE



### find params
POST http://{{host}}/finder

{
  "name" : "coucou",
  "cassette_name" : "K701BT_SE",
  "params" : {
    "color_depth": "8bits",
    "awb": "off",
    "exposure": 60,
    "gain_master": 50,
    "gain_red": 50,
    "gain_green": 10,
    "gain_blue": 0
  }
}


### find params
POST http://127.0.0.1:8080/finder

{
  "name" : "20210713 ",
  "order":"desc",
  "params" : {
    "exposure": [60],    
    "brightness": [5, 10],
    "contrast": [5, 10],
    "saturation": [5, 10],
    "hue": [-1]
  }
}


### find params
POST http://192.168.30.2:8080/finder

{
  "name" : "20210614-search0",
  "params" : {
    "color_depth": "8bits",
    "awb": "off",
    "exposure": 60,
    "gain_master": 50,
    "gain_red": 50,
    "gain_green": 10,
    "gain_blue": 0
  }
}


### get device infos
http://{{host}}/reports

