function drawAllProfilesAndROI(croppedImageProfil, ...
            profileAxis, regionOfInterestLength, ...
            positionsVector, testLinesNumber, halfRectangleWidth)
           
    for p=1:testLinesNumber-1
        
        % draw profil
        drawProfileAndROI(croppedImageProfil, ...
            profileAxis(p), regionOfInterestLength, ...
            positionsVector(1,2) + halfRectangleWidth, positionsVector(p+2,2) + halfRectangleWidth);
    end     
end